[global]
flavor = "mkdocs"
disable = [
  "MD013",
  "MD026",
  "MD036",
  "MD045",
  "MD057",
]

[MD003]
style = "atx"

[MD004]
style = "dash"

[MD033]
allowed = ["div", "iframe", "s"]

[MD041]
front-matter-title-pattern = "^Title:"

[MD046]
style = "fenced"

[MD049]
style = "asterisk"

[MD050]
style = "asterisk"

[MD060]
enabled = true
style = "aligned"

[MD072]
enabled = true
key-order = ["Title", "Date", "Category", "Author", "Aside", "Slug", "Sticky", "Album"]
